### ISSUE TITLE
Publish aggregated metrics on request over HTTP

### ISSUE THREAD

**Issue by fralalonde** [fralalonde/dipstick#4]
- Using minimal dependencies (i.e. httpparse) and a single thread, allow to take peek and reset snapshots of aggregated global metric stats.

REST-style API:
- Line-delimited and / or JSON output encoding, following client `accept:` if specified
- Use request subpath to limit queried metrics
- Use HTTP GET for non-destructive reads, and DELE (???) for resets

A single server should allow querying multiple aggregators (e.g. for 1m / 5m / 15m setups).

**Comment by myfreeweb** [comment]
Please consider the [Prometheus text format](https://prometheus.io/docs/instrumenting/exposition_formats/) to allow Prometheus to take the metrics.

Also an option for the user to write the server manually, e.g. for web server apps (cargo feature to disable the "minimal dependencies" and only have a function that produces the output)

**Comment by fralalonde** [comment]
Thanks for you input! 

Prometheus support was on my list of TODOs, I just created an issue to track it. It should be easy to add.

As for manual publishing, it should already possible to write your own output the same way the existing ones are done, it's just not documented. Another problem is that this an internal contract that could change significantly between releases. I'll think about defining it better.

**Comment by fralalonde** [comment]
Added issue #17

**Comment by fralalonde** [comment]
newly released v0.7 has experimental prometheus text support.
