### ISSUE TITLE
Per-metric sampling for statsd

### ISSUE THREAD

**Issue by mixalturek** [fralalonde/dipstick#44]
It isn't possible to setup also a "local" sampling for a particular counter/timer/... together with "global" one. Errors are typically rare and setting sampling for them would cause very unwanted information loss.

This would require significant API changes just for statsd, but it's also possible using an external configuration (see https://github.com/avast/metrics/pull/22).

**Comment by fralalonde** [comment]
See new `per_metric_sampling.rs` example to see how this can be achieved using the current API.
