### ISSUE TITLE
Upgrade to Rust 2018 edition

### ISSUE THREAD

**Issue by fralalonde** [fralalonde/dipstick#47]

**Comment by Atul9** [comment]
@fralalonde I would like to work on this.

**Comment by fralalonde** [comment]
Be my guest! I'm not sure how much work this entails, feel free to make a single PR or multiple smaller ones.

**Comment by Atul9** [comment]
@fralalonde I have opened up a PR - #54, please check.

**Comment by fralalonde** [comment]
Last merged changes broke different parts of the `make` build (examples, benchmarks, docs) and left  many warnings unfixed, such as

**Comment by fralalonde** [comment]
It seems `cargo fix --edition` only does the easy stuff and leaves much to do.
